In [1]:
import torch

scalar1= torch.tensor([1.])
print(scalar1)

scalar2= torch.tensor([3.])
print(scalar2)

tensor([1.])
tensor([3.])


C:\Users\PC\AppData\Local\Temp\ipykernel_13624\2872556529.py:3: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem . (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
  scalar1= torch.tensor([1.])


In [2]:
torch.add(scalar1, scalar2)

tensor([4.])

In [4]:
torch.sub(scalar1, scalar2)

tensor([-2.])

In [6]:
torch.mul(scalar1, scalar2)

tensor([3.])

In [8]:
torch.div(scalar1, scalar2)

tensor([0.3333])

In [11]:
vector1 = torch.tensor([1., 2., 3.])
print(vector1)

vector2= torch.tensor([4.,5.,6.])

tensor([1., 2., 3.])


In [13]:
div_vector=vector1/vector2
print(div_vector)

tensor([0.2500, 0.4000, 0.5000])


In [14]:
torch.dot(vector1, vector2)

tensor(32.)

In [16]:
matrix1= torch.tensor([[1.,2.], [3., 4.]])
print(matrix1)

matrix2 = torch.tensor([[5., 6.], [7.,8.]])
print(matrix2)

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])


In [18]:
torch.matmul(matrix1, matrix2)

tensor([[19., 22.],
        [43., 50.]])

In [21]:
tensor1=torch.tensor([[[1., 2.], [3.,4.]], [[5., 6.] ,[7., 8.]]])
print(tensor1)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [22]:
tensor2=torch.tensor([[[9., 10.], [11.,12.]], [[13., 14.] ,[15., 16.]]])
print(tensor2)

tensor([[[ 9., 10.],
         [11., 12.]],

        [[13., 14.],
         [15., 16.]]])


In [23]:
sum_tensor = tensor1 +tensor2
print(sum_tensor)

tensor([[[10., 12.],
         [14., 16.]],

        [[18., 20.],
         [22., 24.]]])


In [24]:
div_tensor = tensor1/ tensor2
print(div_tensor)

tensor([[[0.1111, 0.2000],
         [0.2727, 0.3333]],

        [[0.3846, 0.4286],
         [0.4667, 0.5000]]])


In [25]:
torch.sub(tensor1, tensor2)

tensor([[[-8., -8.],
         [-8., -8.]],

        [[-8., -8.],
         [-8., -8.]]])

In [26]:
torch.matmul(tensor1, tensor2)

tensor([[[ 31.,  34.],
         [ 71.,  78.]],

        [[155., 166.],
         [211., 226.]]])